SELECT CR.CAR_ID,
       CR.CAR_TYPE,
       CAST(CR.DAILY_FEE * 30 * (100 - CD.DISCOUNT_RATE) / 100 AS SIGNED) AS FEE
FROM (
    SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR C
    LEFT JOIN (
        SELECT CAR_ID, MIN(START_DATE) AS START_DATE, MAX(END_DATE) AS END_DATE
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        GROUP BY CAR_ID
    ) H ON C.CAR_ID = H.CAR_ID
    WHERE C.CAR_TYPE IN ('세단', 'SUV')
      AND (
          (H.START_DATE IS NULL AND H.END_DATE IS NULL)
          OR (H.END_DATE < '2022-11-01' OR H.START_DATE > '2022-11-30')
      )
) CR
JOIN (
    SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE LEFT(DURATION_TYPE, 2) = '30'
) CD
ON CR.CAR_TYPE = CD.CAR_TYPE
WHERE (CR.DAILY_FEE * 30 * (100 - CD.DISCOUNT_RATE) / 100) >= 500000
  AND (CR.DAILY_FEE * 30 * (100 - CD.DISCOUNT_RATE) / 100) < 2000000
ORDER BY FEE DESC, CR.CAR_TYPE ASC, CR.CAR_ID DESC;