-- 코드를 작성해주세요
SELECT
    ID,
    CASE
        WHEN PERCENTILE <= 0.25 THEN 'CRITICAL'
        WHEN PERCENTILE <= 0.5 THEN 'HIGH'
        WHEN PERCENTILE <= 0.75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM (
    SELECT
        ID,
        CUME_DIST() OVER(ORDER BY SIZE_OF_COLONY DESC) AS PERCENTILE
    FROM ECOLI_DATA
) AS SUB
ORDER BY ID;