SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT OS.USER_ID) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT OS.USER_ID) / TOTAL_USER, 1) AS PURCHASED_RATIO
FROM ONLINE_SALE OS
JOIN (
    SELECT USER_ID, TOTAL_USER
    FROM (
        SELECT YEAR(JOINED) AS YEAR, COUNT(*) AS TOTAL_USER
        FROM USER_INFO
        GROUP BY YEAR(JOINED)
    ) AS A
    JOIN (
        SELECT USER_ID, YEAR(JOINED) AS YEAR
        FROM USER_INFO
        WHERE YEAR(JOINED) = 2021
    ) AS B
    ON A.YEAR = B.YEAR
) AS UI
ON OS.USER_ID = UI.USER_ID
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR, MONTH;