-- 코드를 작성해주세요
SELECT CONCAT(QNUM, 'Q') AS QUARTER, COUNT(ID) AS ECOLI_COUNT
FROM (
    SELECT 
        *,
        QUARTER(DIFFERENTIATION_DATE) AS QNUM
    FROM ECOLI_DATA
) AS Q_ECOLI_DATA
GROUP BY QNUM
ORDER BY QNUM;