-- 코드를 입력하세요
SELECT
    H.HISTORY_ID,
    CASE
        WHEN H.DIFF_DATE >= 90 THEN TRUNCATE(C.DAILY_FEE * H.DIFF_DATE * (100 - DP90.DISCOUNT_RATE) * 0.01, 0)
        WHEN H.DIFF_DATE >= 30 THEN TRUNCATE(C.DAILY_FEE * H.DIFF_DATE * (100 - DP30.DISCOUNT_RATE) * 0.01, 0)
        WHEN H.DIFF_DATE >= 7  THEN TRUNCATE(C.DAILY_FEE * H.DIFF_DATE * (100 - DP7.DISCOUNT_RATE) * 0.01, 0)
        ELSE C.DAILY_FEE * H.DIFF_DATE
    END AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN (
    SELECT HISTORY_ID, CAR_ID, DATEDIFF(END_DATE, START_DATE) + 1 AS DIFF_DATE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) H ON C.CAR_ID = H.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP90 
    ON DP90.CAR_TYPE = '트럭' AND DP90.DURATION_TYPE LIKE '90%'
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP30 
    ON DP30.CAR_TYPE = '트럭' AND DP30.DURATION_TYPE LIKE '30%'
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP7  
    ON DP7.CAR_TYPE = '트럭' AND DP7.DURATION_TYPE LIKE '7%'
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, H.HISTORY_ID DESC;