-- 코드를 입력하세요
SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW AS RR
INNER JOIN MEMBER_PROFILE AS MP
ON RR.MEMBER_ID = MP.MEMBER_ID
WHERE RR.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM (
        SELECT
            MEMBER_ID,
            COUNT(*) AS REVIEW_COUNT,
            RANK() OVER (ORDER BY COUNT(*) DESC) AS RNK
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
    ) AS RANKED
    WHERE RNK = 1
)
ORDER BY RR.REVIEW_DATE, RR.REVIEW_TEXT;