SELECT ORG.YEAR, (MAX_SIZE - SIZE_OF_COLONY) AS YEAR_DEV, ORG.ID
FROM (
    SELECT MAX(SIZE_OF_COLONY) AS MAX_SIZE, YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) AS DEV
INNER JOIN (
    SELECT *, YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
)AS ORG
ON DEV.YEAR = ORG.YEAR
ORDER BY YEAR, YEAR_DEV;
