-- 코드를 작성해주세요
SELECT SUM(HG.SCORE) AS SCORE, HG.EMP_NO, HE.EMP_NAME, HE.POSITION, HE.EMAIL
FROM HR_GRADE AS HG
INNER JOIN HR_EMPLOYEES AS HE
ON HG.EMP_NO = HE.EMP_NO
INNER JOIN HR_DEPARTMENT AS HD
ON HE.DEPT_ID = HD.DEPT_ID
WHERE HG.YEAR = 2022
GROUP BY HG.EMP_NO, HE.EMP_NAME, HE.POSITION, HE.EMAIL
ORDER BY SCORE DESC
LIMIT 1;